[package]
name = "memo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
assert_cmd = "2.0.16"
clap = { version = "4.5.20", features = ["derive"] }
serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.132"
tempfile = "3.13.0"
